name: Robot con Cruces
rules:
  - when:
      red: 0
      green: '*'
      blue: 0
      black: 0
    image: Fondo.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 0
      black: 1
    image: Robot-Al-Norte.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 0
      black: 2
    image: Robot-Al-Este.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 0
      black: 3
    image: Robot-Al-Sur.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 0
      black: 4
    image: Robot-Al-Oeste.png
    text: null
  - when:
      red: 1
      green: 0
      blue: 0
      black: 0
    image: Cruz.png
    text: null
  - when:
      red: 1
      green: 0
      blue: 0
      black: 1
    image: Cruz-y-Robot-Al-Norte.png
    text: null
  - when:
      red: 1
      green: 0
      blue: 0
      black: 2
    image: Cruz-y-Robot-Al-Este.png
    text: null
  - when:
      red: 1
      green: 0
      blue: 0
      black: 3
    image: Cruz-y-Robot-Al-Sur.png
    text: null
  - when:
      red: 1
      green: 0
      blue: 0
      black: 4
    image: Cruz-y-Robot-Al-Oeste.png
    text: null
